### ISSUE TITLE
大佬还更新吗 

### ISSUE THREAD

**Issue by knItalian** [Invinciblelee/HaoReader#1]
很喜欢章节名在下面这个改动，能请问是怎么改的吗 方便吗？ 求教学

**Comment by Invinciblelee** [comment]
还会更新的，只不过最近没时间。

你看PageLoader里面的代码，drawBacground里面改了，widget包里面新增了一个ReadBottomStatusBar类，显示章节电量等信息，然后改了ReadBookActivity的界面。

**Comment by Invinciblelee** [comment]
close
