### ISSUE TITLE
无法导入书源

### ISSUE THREAD

**Issue by ghost** [Invinciblelee/HaoReader#12]
导入网络书源和本地书源便会提示失败，只能新建书源然后粘贴，求修复

**Comment by Invinciblelee** [comment]
能把你导入的书源和网址发我一下吗


 
---原始邮件---
发件人: "917286571"<notifications@github.com>
发送时间: 2019年5月20日(星期一) 凌晨0:21
收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Invinciblelee/MyBookshelf-master] 无法导入书源 (#12)



导入网络书源和本地书源便会提示失败，只能新建书源然后粘贴，求修复

**Comment by 917286571** [comment]
https://github.com/Invinciblelee/MyBookshelf-master/issues/12#issuecomment-493804447

**Comment by 917286571** [comment]
https://gitee.com/gekunfei/web/raw/master/myBookshelf/bookSource_176

**Comment by 917286571** [comment]
> 能把你导入的书源和网址发我一下吗
> […](#)
> ---原始邮件--- 发件人: "917286571"<notifications@github.com> 发送时间: 2019年5月20日(星期一) 凌晨0:21 收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>; 抄送: "Subscribed"<subscribed@noreply.github.com>; 主题: [Invinciblelee/MyBookshelf-master] 无法导入书源 (#12) 导入网络书源和本地书源便会提示失败，只能新建书源然后粘贴，求修复 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

https://github.com/Invinciblelee/MyBookshelf-master/issues/12#issuecomment-493804447

**Comment by 917286571** [comment]
> https://gitee.com/gekunfei/web/raw/master/myBookshelf/bookSource_176

**Comment by ghost** [comment]
> 能把你导入的书源和网址发我一下吗
> […](#)
> -“Invinciblelee/MyBookshelf-master”<MyBookshelf-master@noreply.github.com>；：原始邮件-发件人：“917286571”抄送：“订阅”<订阅@norespony.github.com>；主题：[Invinciblelee/MyBook大陆架-master]无法导入书源(#12)导入网络书源和本地书源便会提示失败，只能新建书源然后粘贴，求修复-您收到这个消息是因为您订阅了这个线程。直接回复这封电子邮件，在GitHub上查看它，或静音线程。

https://github.com/Invinciblelee/MyBookshelf-master/issues/12#issuecomment-493804447

**Comment by Invinciblelee** [comment]
> > 能把你导入的书源和网址发我一下吗
> > […](#)
> > -“Invinciblelee/MyBookshelf-master”[MyBookshelf-master@noreply.github.com](mailto:MyBookshelf-master@noreply.github.com)；：原始邮件-发件人：“917286571”抄送：“订阅”<订阅@norespony.github.com>；主题：[Invinciblelee/MyBook大陆架-master]无法导入书源(#12)导入网络书源和本地书源便会提示失败，只能新建书源然后粘贴，求修复-您收到这个消息是因为您订阅了这个线程。直接回复这封电子邮件，在GitHub上查看它，或静音线程。
> 
> [#12 (comment)](https://github.com/Invinciblelee/MyBookshelf-master/issues/12#issuecomment-493804447)

我知道了，已经修复了，还没发版本
