### ISSUE TITLE
一些书源有问题

### ISSUE THREAD

**Issue by hokk012as** [Invinciblelee/HaoReader#13]
{
  "bookSourceCacheEnabled": false,
  "bookSourceGroup": "",
  "bookSourceName": "一起品小说网",
  "bookSourceRuleType": "DEFAULT",
  "bookSourceType": "TEXT",
  "bookSourceUrl": "http://www.17pxs.com",
  "checkUrl": "",
  "enable": true,
  "httpUserAgent": "",
  "ruleBookAuthor": "",
  "ruleBookContent": "class.articlecontent@textNodes",
  "ruleBookName": "",
  "ruleChapterList": "class.ml_list@tag.ul@tag.li@tag.a",
  "ruleChapterName": "text",
  "ruleChapterUrl": "",
  "ruleChapterUrlNext": "",
  "ruleContentUrl": "href",
  "ruleContentUrlNext": "",
  "ruleCoverUrl": "class.pic@tag.img.0@src",
  "ruleFindUrl": "",
  "ruleIntroduce": "class.introduce@class.jj@textNodes",
  "ruleLastChapter": "",
  "rulePersistedVariables": "",
  "ruleSearchAuthor": "class.odd.1@text|class.catalog@tag.p.1@tag.span.1@tag.a.0@text",
  "ruleSearchCoverUrl": "class.catalog@class.pic@tag.img.0@src",
  "ruleSearchKind": "class.even.2@text|class.catalog@tag.p.1@tag.span.2@text#状态：",
  "ruleSearchLastChapter": "class.even.0@tag.a.0@text|class.ml_content@tag.ul.0@tag.li.0@tag.a.0@text",
  "ruleSearchList": "class.grid@tag.tr!0|class.main",
  "ruleSearchName": "class.odd.0@tag.a.0@text|class.catalog@tag.h1.0@text",
  "ruleSearchNoteUrl": "class.odd.0@tag.a.0@href",
  "ruleSearchUrl": "http://www.17pxs.com/modules/article/search.php@searchkey=searchKey&submit=点击搜索|char=gbk",
  "serialNumber": 2,
  "weight": 47
}
post的书源有些有问题，无法搜索。。。

**Comment by Invinciblelee** [comment]
> {
> "bookSourceCacheEnabled": false,
> "bookSourceGroup": "",
> "bookSourceName": "一起品小说网",
> "bookSourceRuleType": "DEFAULT",
> "bookSourceType": "TEXT",
> "bookSourceUrl": "http://www.17pxs.com",
> "checkUrl": "",
> "enable": true,
> "httpUserAgent": "",
> "ruleBookAuthor": "",
> "ruleBookContent": "class.articlecontent@textNodes",
> "ruleBookName": "",
> "ruleChapterList": "class.ml_list@tag.ul@[tag.li@tag.a](mailto:tag.li@tag.a)",
> "ruleChapterName": "text",
> "ruleChapterUrl": "",
> "ruleChapterUrlNext": "",
> "ruleContentUrl": "href",
> "ruleContentUrlNext": "",
> "ruleCoverUrl": "class.pic@tag.img.0@src",
> "ruleFindUrl": "",
> "ruleIntroduce": "class.introduce@class.jj@textNodes",
> "ruleLastChapter": "",
> "rulePersistedVariables": "",
> "ruleSearchAuthor": "class.odd.1@text|class.catalog@tag.p.1@tag.span.1@tag.a.0@text",
> "ruleSearchCoverUrl": "class.catalog@class.pic@tag.img.0@src",
> "ruleSearchKind": "class.even.2@text|class.catalog@tag.p.1@tag.span.2@text#状态：",
> "ruleSearchLastChapter": "class.even.0@tag.a.0@text|class.ml_content@tag.ul.0@tag.li.0@tag.a.0@text",
> "ruleSearchList": "[class.grid@tag.tr](mailto:class.grid@tag.tr)!0|class.main",
> "ruleSearchName": "class.odd.0@tag.a.0@text|class.catalog@tag.h1.0@text",
> "ruleSearchNoteUrl": "class.odd.0@tag.a.0@href",
> "ruleSearchUrl": "[http://www.17pxs.com/modules/article/search.php@searchkey=searchKey&submit=点击搜索|char=gbk](http://www.17pxs.com/modules/article/search.php@searchkey=searchKey&submit=%E7%82%B9%E5%87%BB%E6%90%9C%E7%B4%A2%7Cchar=gbk)",
> "serialNumber": 2,
> "weight": 47
> }
> post的书源有些有问题，无法搜索。。。

不是post的问题，规则不能用|连接，改成||，其他也一样，&改成&&， %改成%%

**Comment by hokk012as** [comment]
明白了，谢谢:smile:
