### ISSUE TITLE
听书的书源有吗

### ISSUE THREAD

**Issue by FoxNick** [Invinciblelee/HaoReader#2]
听书的书源有吗

**Comment by Invinciblelee** [comment]
里面有声的分组都可以用------------------ 原始邮件 ------------------
发件人: "FoxNick"<notifications@github.com>
发送时间: 2019年5月11日(星期六) 下午5:03
收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Invinciblelee/MyBookshelf-master] 听书的书源有吗 (#2)



听书的书源有吗
 
&mdash;

**Comment by 643070581** [comment]
有的！！

**Comment by FoxNick** [comment]
给发份
