### ISSUE TITLE
详情页换源失败  

### ISSUE THREAD

**Issue by FoxNick** [Invinciblelee/HaoReader#7]
详情页换源失败  同样的书源阅读页能换  这里总是出错  原因不明   有时候能换  有时候换不了

**Comment by Invinciblelee** [comment]
> 详情页换源失败 同样的书源阅读页能换 这里总是出错 原因不明 有时候能换 有时候换不了

我优化了下换源的代码，你再试试

**Comment by Invinciblelee** [comment]
> 详情页换源失败 同样的书源阅读页能换 这里总是出错 原因不明 有时候能换 有时候换不了

你的内置书旗书源提交下呗，找不到那个Defaultsq类

**Comment by FoxNick** [comment]
提交了




------------------ 原始邮件 ------------------
发件人: "LiZhanPing"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 中午11:04
收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>; 
抄送: "☆爱的凌迟☆"<354435383@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)



 
详情页换源失败 同样的书源阅读页能换 这里总是出错 原因不明 有时候能换 有时候换不了
  
你的内置书旗书源提交下呗，找不到那个Defaultsq类

**Comment by FoxNick** [comment]
My716的书源 你修改过？ 怎么搜不到书？




------------------ 原始邮件 ------------------
发件人: "LiZhanPing"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 中午11:04
收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>; 
抄送: "☆爱的凌迟☆"<354435383@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)



 
详情页换源失败 同样的书源阅读页能换 这里总是出错 原因不明 有时候能换 有时候换不了
  
你的内置书旗书源提交下呗，找不到那个Defaultsq类

**Comment by Invinciblelee** [comment]
能搜啊，你没开启吧


 
---原始邮件---
发件人: "FoxNick"<notifications@github.com>
发送时间: 2019年5月17日(星期五) 中午1:09
收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;
抄送: "LiZhanPing"<1760316362@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)


My716的书源 你修改过？ 怎么搜不到书？ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "LiZhanPing"<notifications@github.com>;  
 发送时间: 2019年5月17日(星期五) 中午11:04 
 收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;  
 抄送: "☆爱的凌迟☆"<354435383@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7) 
 
 
 
   
 详情页换源失败 同样的书源阅读页能换 这里总是出错 原因不明 有时候能换 有时候换不了 
    
 你的内置书旗书源提交下呗，找不到那个Defaultsq类

**Comment by FoxNick** [comment]
听书的书源 发一份




------------------ 原始邮件 ------------------
发件人: "LiZhanPing"<notifications@github.com>; 
发送时间: 2019年5月17日(星期五) 中午1:30
收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>; 
抄送: "☆爱的凌迟☆"<354435383@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)



能搜啊，你没开启吧 
 
 
   
 ---原始邮件--- 
 发件人: "FoxNick"<notifications@github.com> 
 发送时间: 2019年5月17日(星期五) 中午1:09 
 收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>; 
 抄送: "LiZhanPing"<1760316362@qq.com>;"Comment"<comment@noreply.github.com>; 
 主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7) 
 
 
 My716的书源 你修改过？ 怎么搜不到书？  
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: "LiZhanPing"<notifications@github.com>;   
  发送时间: 2019年5月17日(星期五) 中午11:04  
  收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;   
  抄送: "☆爱的凌迟☆"<354435383@qq.com>; "Author"<author@noreply.github.com>;   
  主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)  
   
   
   
     
  详情页换源失败 同样的书源阅读页能换 这里总是出错 原因不明 有时候能换 有时候换不了  
      
  你的内置书旗书源提交下呗，找不到那个Defaultsq类

**Comment by Invinciblelee** [comment]
---原始邮件---
发件人: "FoxNick"<notifications@github.com>
发送时间: 2019年5月17日(星期五) 中午1:36
收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;
抄送: "LiZhanPing"<1760316362@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)


听书的书源 发一份 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "LiZhanPing"<notifications@github.com>;  
 发送时间: 2019年5月17日(星期五) 中午1:30 
 收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;  
 抄送: "☆爱的凌迟☆"<354435383@qq.com>; "Author"<author@noreply.github.com>;  
 主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7) 
 
 
 
 能搜啊，你没开启吧  
   
   
     
  ---原始邮件---  
  发件人: "FoxNick"<notifications@github.com>  
  发送时间: 2019年5月17日(星期五) 中午1:09  
  收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;  
  抄送: "LiZhanPing"<1760316362@qq.com>;"Comment"<comment@noreply.github.com>;  
  主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)  
   
   
  My716的书源 你修改过？ 怎么搜不到书？   
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: "LiZhanPing"<notifications@github.com>;    
   发送时间: 2019年5月17日(星期五) 中午11:04   
   收件人: "Invinciblelee/MyBookshelf-master"<MyBookshelf-master@noreply.github.com>;    
   抄送: "☆爱的凌迟☆"<354435383@qq.com>; "Author"<author@noreply.github.com>;    
   主题: Re: [Invinciblelee/MyBookshelf-master] 详情页换源失败   (#7)   
     
     
     
       
   详情页换源失败 同样的书源阅读页能换 这里总是出错 原因不明 有时候能换 有时候换不了   
        
   你的内置书旗书源提交下呗，找不到那个Defaultsq类
